# Generated by pip2nix 0.8.0.dev1
# See https://github.com/nix-community/pip2nix

{ pkgs, fetchurl, fetchgit, fetchhg ,fetchPypi, mujoco210}:

self: super: {
  "mujoco_py" = super.buildPythonPackage rec {
    pname = "mujoco-py";
    version = "2.1.12.14";  # or your version
    format = "setuptools";
    src = pkgs.fetchFromGitHub {
      owner = "openai";
      repo = "mujoco-py";
      rev = "f1312cc";
      sha256 = "sha256-nwIJzLPhTZNlwk/NAiWCV/zYdwKeuQqhW6UIniGw8+k=";
    };

    propagatedBuildInputs = [
      self."numpy"
      self."cffi"
      self."glfw"
      self."fasteners"
      self."imageio"
      self."lockfile"
    ];
    nativeBuildInputs =  [
      self."cython"
    ];
    preBuild = ''
      export MUJOCO_PY_MUJOCO_PATH=${mujoco210}
      export MUJOCO_PY_MJKEY_PATH=${mujoco210}/mjkey.txt
      export LD_LIBRARY_PATH=${mujoco210}/bin:$LD_LIBRARY_PATH
      echo "MUJOCO_PY_MUJOCO_PATH during build: $MUJOCO_PY_MUJOCO_PATH"
      echo "LD_LIBRARY_PATH during build: $LD_LIBRARY_PATH"
    '';
    makeWrapperArgs = [
      "--set MUJOCO_PY_MUJOCO_PATH ${mujoco210}"
      "--set MUJOCO_PY_MJKEY_PATH ${mujoco210}/mjkey.txt"
    ];
  };
  "cython" = super.buildPythonPackage rec {
    pname = "cython";
    version = "0.29.24";
    src = fetchPypi {
      inherit (pname version);
      sha256 = "sha256-zfBNB8NgCGDowuuq1Oj1KsP+shJFPBdkpJrAjIJ+hEM=";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "annotated-types" = super.buildPythonPackage rec {
    pname = "annotated-types";
    version = "0.7.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/78/b6/6307fbef88d9b5ee7421e68d78a9f162e0da4900bc5f5793f6d3d0e34fb8/annotated_types-0.7.0-py3-none-any.whl";
      sha256 = "0lrab0f3lgvpbj79p178xd7cn6qkr2zz9w6lw3rw7fwg7asfh0hz";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "astroid" = super.buildPythonPackage rec {
    pname = "astroid";
    version = "3.3.9";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/de/80/c749efbd8eef5ea77c7d6f1956e8fbfb51963b7f93ef79647afd4d9886e3/astroid-3.3.9-py3-none-any.whl";
      sha256 = "0j0jhflh4dwdj03rfr5hms5167mwv6vjha127va7nsm9rc5gsnyh";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."typing-extensions"
    ];
  };
  "asttokens" = super.buildPythonPackage rec {
    pname = "asttokens";
    version = "3.0.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/25/8a/c46dcc25341b5bce5472c718902eb3d38600a903b14fa6aeecef3f21a46f/asttokens-3.0.0-py3-none-any.whl";
      sha256 = "1qiji79gk427xgsnl4zzybpha323wq3cgccc2gars6arl18q61z3";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "autopep8" = super.buildPythonPackage rec {
    pname = "autopep8";
    version = "2.3.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/9e/43/53afb8ba17218f19b77c7834128566c5bbb100a0ad9ba2e8e89d089d7079/autopep8-2.3.2-py2.py3-none-any.whl";
      sha256 = "0a0inplz6x0wr7kscxw1xw2jpv1mnqarqqp27l65m11ccycd92nf";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."pycodestyle"
      self."tomli"
    ];
  };
  "certifi" = super.buildPythonPackage rec {
    pname = "certifi";
    version = "2025.4.26";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/4a/7e/3db2bd1b1f9e95f7cddca6d6e75e2f2bd9f51b1246e546d88addca0106bd/certifi-2025.4.26-py3-none-any.whl";
      sha256 = "1wq530qla8qwn8am1bf221jhriqmd8rn6b4594k1cwg3vxj06d9h";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "cffi" = super.buildPythonPackage rec {
    pname = "cffi";
    version = "1.17.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/fc/97/c783634659c2920c3fc70419e3af40972dbaf758daa229a7d6ea6135c90d/cffi-1.17.1.tar.gz";
      sha256 = "0918qn4yfjfgcy7i4imfy9q1cvl3svmm06anakflig1jdh0wcf8w";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."pycparser"
    ];
  };
  "charset-normalizer" = super.buildPythonPackage rec {
    pname = "charset-normalizer";
    version = "3.4.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/16/b0/572805e227f01586461c80e0fd25d65a2115599cc9dad142fee4b747c357/charset_normalizer-3.4.1.tar.gz";
      sha256 = "18sfsqpdmxbddr3g3yg0sln10ghq4sp0vl2xb1b5p9v8rlc1y9a4";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "click" = super.buildPythonPackage rec {
    pname = "click";
    version = "8.1.8";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/7e/d4/7ebdbd03970677812aac39c869717059dbb71a4cfc033ca6e5221787892c/click-8.1.8-py3-none-any.whl";
      sha256 = "1ck3f812hql67a8bfafkq30xjqmvjzsd38hjcyh7h5fhpsxk5hb3";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "cloudpickle" = super.buildPythonPackage rec {
    pname = "cloudpickle";
    version = "3.1.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/7e/e8/64c37fadfc2816a7701fa8a6ed8d87327c7d54eacfbfb6edab14a2f2be75/cloudpickle-3.1.1-py3-none-any.whl";
      sha256 = "03imd2k6adyzrj3hxrc8z6v9fwlw188blh5dkpp334q3jm1a9if8";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "comm" = super.buildPythonPackage rec {
    pname = "comm";
    version = "0.2.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/e6/75/49e5bfe642f71f272236b5b2d2691cf915a7283cc0ceda56357b61daa538/comm-0.2.2-py3-none-any.whl";
      sha256 = "1lv41agh1igr7l3f86s4y5k40fyysqv7skn1r7l1wrpzf35qdyz6";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."traitlets"
    ];
  };
  "contourpy" = super.buildPythonPackage rec {
    pname = "contourpy";
    version = "1.3.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/f5/f6/31a8f28b4a2a4fa0e01085e542f3081ab0588eff8e589d39d775172c9792/contourpy-1.3.0.tar.gz";
      sha256 = "191q34pbbm984jvlv462jaw9dnb28ddckl7g4yqzza0pfyqhvykz";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."numpy"
    ];
  };
  "cycler" = super.buildPythonPackage rec {
    pname = "cycler";
    version = "0.12.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/e7/05/c19819d5e3d95294a6f5947fb9b9629efb316b96de511b418c53d245aae6/cycler-0.12.1-py3-none-any.whl";
      sha256 = "0c0d9s2mmb6b7jnbhnclb5017rbjb530i62jc50n9n12yb7zgkl5";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "debugpy" = super.buildPythonPackage rec {
    pname = "debugpy";
    version = "1.8.14";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/bd/75/087fe07d40f490a78782ff3b0a30e3968936854105487decdb33446d4b0e/debugpy-1.8.14.tar.gz";
      sha256 = "08jkxp99glb9fp09h62kb4gbndsq228aqq4bm986hh8q8cc8glkw";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "decorator" = super.buildPythonPackage rec {
    pname = "decorator";
    version = "5.2.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/4e/8c/f3147f5c4b73e7550fe5f9352eaa956ae838d5c51eb58e7a25b9f3e2643b/decorator-5.2.1-py3-none-any.whl";
      sha256 = "0jp0r2hhdhdgfrmdfb191qj0kz02cm60ii5w78mjv7idb90vn5nk";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "dill" = super.buildPythonPackage rec {
    pname = "dill";
    version = "0.4.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/50/3d/9373ad9c56321fdab5b41197068e1d8c25883b3fea29dd361f9b55116869/dill-0.4.0-py3-none-any.whl";
      sha256 = "0j8hav3ijfw861rkcb5y1n0ak41n2vml70jfq5j88b1c87v4pxa4";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "docker-pycreds" = super.buildPythonPackage rec {
    pname = "docker-pycreds";
    version = "0.4.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/f5/e8/f6bd1eee09314e7e6dee49cbe2c5e22314ccdb38db16c9fc72d2fa80d054/docker_pycreds-0.4.0-py2.py3-none-any.whl";
      sha256 = "0jdg6wynr0lvw4l2m4fmnz9049vj1p6ikv06a406hy32d0j12rkj";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."six"
    ];
  };
  "eval-type-backport" = super.buildPythonPackage rec {
    pname = "eval-type-backport";
    version = "0.2.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ce/31/55cd413eaccd39125368be33c46de24a1f639f2e12349b0361b4678f3915/eval_type_backport-0.2.2-py3-none-any.whl";
      sha256 = "02hv254h2d6r9j1r4s3gz660l3x85r0x0mnljrplfzsijg1xfsnb";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "exceptiongroup" = super.buildPythonPackage rec {
    pname = "exceptiongroup";
    version = "1.2.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/02/cc/b7e31358aac6ed1ef2bb790a9746ac2c69bcb3c8588b41616914eb106eaf/exceptiongroup-1.2.2-py3-none-any.whl";
      sha256 = "0nvrlxd5i42ri3zd6ddi7xb478jbw4iy25pmz31bwf62678vj49i";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "executing" = super.buildPythonPackage rec {
    pname = "executing";
    version = "2.2.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/7b/8f/c4d9bafc34ad7ad5d8dc16dd1347ee0e507a52c3adb6bfa8887e1c6a26ba/executing-2.2.0-py2.py3-none-any.whl";
      sha256 = "1ankzzn59fxgqcry4vwsnf44ibcz6g9m6yija0kxd26kr9872f0i";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "farama-notifications" = super.buildPythonPackage rec {
    pname = "farama-notifications";
    version = "0.0.4";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/05/2c/ffc08c54c05cdce6fbed2aeebc46348dbe180c6d2c541c7af7ba0aa5f5f8/Farama_Notifications-0.0.4-py3-none-any.whl";
      sha256 = "1bh5mwn1lxaag7siwy857la2lxl0z73isdjnq3vn26d46l897phl";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "flake8" = super.buildPythonPackage rec {
    pname = "flake8";
    version = "7.2.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/83/5c/0627be4c9976d56b1217cb5187b7504e7fd7d3503f8bfd312a04077bd4f7/flake8-7.2.0-py2.py3-none-any.whl";
      sha256 = "0hq3qhv084vvzmhxlak3b45d07rnm69kpyhlvak581xnpnjjpfck";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."mccabe"
      self."pycodestyle"
      self."pyflakes"
    ];
  };
  "fonttools" = super.buildPythonPackage rec {
    pname = "fonttools";
    version = "4.57.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/03/2d/a9a0b6e3a0cf6bd502e64fc16d894269011930cabfc89aee20d1635b1441/fonttools-4.57.0.tar.gz";
      sha256 = "1pj2pkyh77vz8iys9bhimizf2rhasvamvl9rsafjzgk5w08cwzkj";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "gitdb" = super.buildPythonPackage rec {
    pname = "gitdb";
    version = "4.0.12";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/a0/61/5c78b91c3143ed5c14207f463aecfc8f9dbb5092fb2869baf37c273b2705/gitdb-4.0.12-py3-none-any.whl";
      sha256 = "1kwvpnwzlqn1lkvld2a25vm4wjjmgiq3xk35cln9a02ljlakw1v7";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."smmap"
    ];
  };
  "gitpython" = super.buildPythonPackage rec {
    pname = "gitpython";
    version = "3.1.44";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/1d/9a/4114a9057db2f1462d5c8f8390ab7383925fe1ac012eaa42402ad65c2963/GitPython-3.1.44-py3-none-any.whl";
      sha256 = "040i04lfvwvdbxc7zka16aacka9qgq7favcspijfxldym76i03ly";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."gitdb"
    ];
  };
  "gymnasium" = super.buildPythonPackage rec {
    pname = "gymnasium";
    version = "1.1.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/f9/68/2bdc7b46b5f543dd865575f9d19716866bdb76e50dd33b71ed1a3dd8bb42/gymnasium-1.1.1-py3-none-any.whl";
      sha256 = "12ljxf3n9cvvcd65ff0rnzszfli5rm4jhfzn6xp6d25klb07w5lw";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."cloudpickle"
      self."farama-notifications"
      self."importlib-metadata"
      self."numpy"
      self."typing-extensions"
    ];
  };
  "idna" = super.buildPythonPackage rec {
    pname = "idna";
    version = "3.10";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/76/c6/c88e154df9c4e1a2a66ccf0005a88dfb2650c1dffb6f5ce603dfbd452ce3/idna-3.10-py3-none-any.whl";
      sha256 = "1lw72a5swas501zvkpd6dsryj5hzjijqxs3526kbp7151md1jvcl";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "importlib-metadata" = super.buildPythonPackage rec {
    pname = "importlib-metadata";
    version = "8.7.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/20/b0/36bd937216ec521246249be3bf9855081de4c5e06a0c9b4219dbeda50373/importlib_metadata-8.7.0-py3-none-any.whl";
      sha256 = "1z9ay32p0j6k05qjm5065l0f2l2dk00fy7356258cxsci58ibpg5";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."zipp"
    ];
  };
  "importlib-resources" = super.buildPythonPackage rec {
    pname = "importlib-resources";
    version = "6.5.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/a4/ed/1f1afb2e9e7f38a545d628f864d562a5ae64fe6f7a10e28ffb9b185b4e89/importlib_resources-6.5.2-py3-none-any.whl";
      sha256 = "1v6cc2kxi319k1d0k77psninkv8wflk83jval1kqpir8xp1zv73q";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."zipp"
    ];
  };
  "iniconfig" = super.buildPythonPackage rec {
    pname = "iniconfig";
    version = "2.1.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/2c/e1/e6716421ea10d38022b952c159d5161ca1193197fb744506875fbb87ea7b/iniconfig-2.1.0-py3-none-any.whl";
      sha256 = "0q5piqbflf6jz0zd67lvmfzlrj9m96zwd0am8dvhwf0j6drabswx";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "ipykernel" = super.buildPythonPackage rec {
    pname = "ipykernel";
    version = "6.29.5";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/94/5c/368ae6c01c7628438358e6d337c19b05425727fbb221d2a3c4303c372f42/ipykernel-6.29.5-py3-none-any.whl";
      sha256 = "1d910jhvgbwhjq652fcb1srvpzjamqlar6rpj6dv0m53bax6dnxg";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."comm"
      self."debugpy"
      self."ipython"
      self."jupyter-client"
      self."jupyter-core"
      self."matplotlib-inline"
      self."nest-asyncio"
      self."packaging"
      self."psutil"
      self."pyzmq"
      self."tornado"
      self."traitlets"
    ];
  };
  "ipython" = super.buildPythonPackage rec {
    pname = "ipython";
    version = "8.18.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/47/6b/d9fdcdef2eb6a23f391251fde8781c38d42acd82abe84d054cb74f7863b0/ipython-8.18.1-py3-none-any.whl";
      sha256 = "15x3kblhabwy240r4ja7sq5ch2m9m8lqlzqpq5g9b09dswcp89p8";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."decorator"
      self."exceptiongroup"
      self."jedi"
      self."matplotlib-inline"
      self."pexpect"
      self."prompt-toolkit"
      self."pygments"
      self."stack-data"
      self."traitlets"
      self."typing-extensions"
    ];
  };
  "isort" = super.buildPythonPackage rec {
    pname = "isort";
    version = "6.0.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/c1/11/114d0a5f4dabbdcedc1125dee0888514c3c3b16d3e9facad87ed96fad97c/isort-6.0.1-py3-none-any.whl";
      sha256 = "05cn3szb8k47fvasm5xw51rwdvi0ldhr3hnzi16djy4nbkvdgi9d";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "jedi" = super.buildPythonPackage rec {
    pname = "jedi";
    version = "0.19.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/c0/5a/9cac0c82afec3d09ccd97c8b6502d48f165f9124db81b4bcb90b4af974ee/jedi-0.19.2-py2.py3-none-any.whl";
      sha256 = "1fdmxpv6wnyf7kg88irbyzd7925m7k4a70bnbkz5f3s9x2yj5vx8";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."parso"
    ];
  };
  "jupyter-client" = super.buildPythonPackage rec {
    pname = "jupyter-client";
    version = "8.6.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/11/85/b0394e0b6fcccd2c1eeefc230978a6f8cb0c5df1e4cd3e7625735a0d7d1e/jupyter_client-8.6.3-py3-none-any.whl";
      sha256 = "0gzjx04cpwm59zlha2ac9d18bbzk23s1aa9nqdd90ifchv4rr8g8";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."importlib-metadata"
      self."jupyter-core"
      self."python-dateutil"
      self."pyzmq"
      self."tornado"
      self."traitlets"
    ];
  };
  "jupyter-core" = super.buildPythonPackage rec {
    pname = "jupyter-core";
    version = "5.7.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/c9/fb/108ecd1fe961941959ad0ee4e12ee7b8b1477247f30b1fdfd83ceaf017f0/jupyter_core-5.7.2-py3-none-any.whl";
      sha256 = "02blpl0hlyxmkv95j7ydb7j0lxms5rvlcvnbwziz5g5lyv91awsg";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."platformdirs"
      self."traitlets"
    ];
  };
  "kiwisolver" = super.buildPythonPackage rec {
    pname = "kiwisolver";
    version = "1.4.7";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/85/4d/2255e1c76304cbd60b48cee302b66d1dde4468dc5b1160e4b7cb43778f2a/kiwisolver-1.4.7.tar.gz";
      sha256 = "0q0ak10hwlyza21qhjkfq97xpaixb337q0fkhnvgf1vipn0zz4wq";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "matplotlib" = super.buildPythonPackage rec {
    pname = "matplotlib";
    version = "3.9.4";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/df/17/1747b4154034befd0ed33b52538f5eb7752d05bb51c5e2a31470c3bc7d52/matplotlib-3.9.4.tar.gz";
      sha256 = "1hqvlhxh4slh1g3b2p989f0q6gng0ax6z2psxmpxrjwkffzfh00y";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."contourpy"
      self."cycler"
      self."fonttools"
      self."importlib-resources"
      self."kiwisolver"
      self."numpy"
      self."packaging"
      self."pillow"
      self."pyparsing"
      self."python-dateutil"
    ];
  };
  "matplotlib-inline" = super.buildPythonPackage rec {
    pname = "matplotlib-inline";
    version = "0.1.7";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/8f/8e/9ad090d3553c280a8060fbf6e24dc1c0c29704ee7d1c372f0c174aa59285/matplotlib_inline-0.1.7-py3-none-any.whl";
      sha256 = "1jjk0v6c4a7aw2247a0gy2cm1k2z7yhycwjxi6qj33zzlhwjs6fz";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."traitlets"
    ];
  };
  "mccabe" = super.buildPythonPackage rec {
    pname = "mccabe";
    version = "0.7.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/27/1a/1f68f9ba0c207934b35b86a8ca3aad8395a3d6dd7921c0686e23853ff5a9/mccabe-0.7.0-py2.py3-none-any.whl";
      sha256 = "0vkv89izh5asv85wlgbfdkfynd6qy2s0f63q35ls9r70dfmk0bbc";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "nest-asyncio" = super.buildPythonPackage rec {
    pname = "nest-asyncio";
    version = "1.6.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/a0/c4/c2971a3ba4c6103a3d10c4b0f24f461ddc027f0f09763220cf35ca1401b3/nest_asyncio-1.6.0-py3-none-any.whl";
      sha256 = "071fhnqhaagz3bhcl0qpslsjyarfqrjyyxq40n0pr2aydgynxbw7";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "numpy" = super.buildPythonPackage rec {
    pname = "numpy";
    version = "2.0.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/a9/75/10dd1f8116a8b796cb2c737b674e02d02e80454bda953fa7e65d8c12b016/numpy-2.0.2.tar.gz";
      sha256 = "0y3fcd268cnrc8ipcmj1c082an4j4a4wj3dbcjlf500qxryrhg48";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "packaging" = super.buildPythonPackage rec {
    pname = "packaging";
    version = "25.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/20/12/38679034af332785aac8774540895e234f4d07f7545804097de4b666afd8/packaging-25.0-py3-none-any.whl";
      sha256 = "1154669ydc149dash6yaf3n2byqiqvajf8isdc282xgin7r2wmr9";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "parso" = super.buildPythonPackage rec {
    pname = "parso";
    version = "0.8.4";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/c6/ac/dac4a63f978e4dcb3c6d3a78c4d8e0192a113d288502a1216950c41b1027/parso-0.8.4-py2.py3-none-any.whl";
      sha256 = "061zsi1hchimzjzi538yxrw16yf3qmvw706wvp9aq7994056f654";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "pexpect" = super.buildPythonPackage rec {
    pname = "pexpect";
    version = "4.9.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/9e/c3/059298687310d527a58bb01f3b1965787ee3b40dce76752eda8b44e9a2c5/pexpect-4.9.0-py2.py3-none-any.whl";
      sha256 = "08rm4mza8w0f45hd1qd72a9cyapp1bn6qciyvki6p4z4h3hd2dkj";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."ptyprocess"
    ];
  };
  "pillow" = super.buildPythonPackage rec {
    pname = "pillow";
    version = "11.2.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/af/cb/bb5c01fcd2a69335b86c22142b2bccfc3464087efb7fd382eee5ffc7fdf7/pillow-11.2.1.tar.gz";
      sha256 = "1dhnhyjpk22q9vvjaaacxjdvllsqm39p76wpxyvnfqs1k0cxckd6";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "pip" = super.buildPythonPackage rec {
    pname = "pip";
    version = "25.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/e0/f0/8a2806114cd36e282823fd4d8e88e3b94dc943c2569c350d0c826a49db38/pip-25.1-py3-none-any.whl";
      sha256 = "1fhn1bzry0k64ab9pn0j1q42saqalz1a3j5y24504mfhm85amd0k";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "platformdirs" = super.buildPythonPackage rec {
    pname = "platformdirs";
    version = "4.3.7";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/6d/45/59578566b3275b8fd9157885918fcd0c4d74162928a5310926887b856a51/platformdirs-4.3.7-py3-none-any.whl";
      sha256 = "150asj0cx2kaihgfp84mm183m8f7pbsdins9ql9nz51i8crpaf50";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "pluggy" = super.buildPythonPackage rec {
    pname = "pluggy";
    version = "1.5.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/88/5f/e351af9a41f866ac3f1fac4ca0613908d9a41741cfcf2228f4ad853b697d/pluggy-1.5.0-py3-none-any.whl";
      sha256 = "0sd6bvbvjd93ad04fmadmdk35rhv1wz5y5ky6zk2s06ar29avqa4";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "prompt-toolkit" = super.buildPythonPackage rec {
    pname = "prompt-toolkit";
    version = "3.0.51";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ce/4f/5249960887b1fbe561d9ff265496d170b55a735b76724f10ef19f9e40716/prompt_toolkit-3.0.51-py3-none-any.whl";
      sha256 = "01vv0zdvh3qfakclixjq37jw8ykxvvqlr6ig7r12skp8zl8jjx2j";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."wcwidth"
    ];
  };
  "protobuf" = super.buildPythonPackage rec {
    pname = "protobuf";
    version = "6.30.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/c8/8c/cf2ac658216eebe49eaedf1e06bc06cbf6a143469236294a1171a51357c3/protobuf-6.30.2.tar.gz";
      sha256 = "0j507gmbdq3bmkpvdqnnbra8d3b3b5g9xd959h2md33d0yp5kj1m";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "psutil" = super.buildPythonPackage rec {
    pname = "psutil";
    version = "7.0.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/2a/80/336820c1ad9286a4ded7e845b2eccfcb27851ab8ac6abece774a6ff4d3de/psutil-7.0.0.tar.gz";
      sha256 = "0mn42p9pzh0wynhk9i18iyvp8h54hbcsyczajmjcpv4blgmw7sbv";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "ptyprocess" = super.buildPythonPackage rec {
    pname = "ptyprocess";
    version = "0.7.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/22/a6/858897256d0deac81a172289110f31629fc4cee19b6f01283303e18c8db3/ptyprocess-0.7.0-py2.py3-none-any.whl";
      sha256 = "0dgg5x4nvdpfiz552diy11xg72y14s38hjz9qxygafnfgybg6hab";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "pure-eval" = super.buildPythonPackage rec {
    pname = "pure-eval";
    version = "0.2.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/8e/37/efad0257dc6e593a18957422533ff0f87ede7c9c6ea010a2177d738fb82f/pure_eval-0.2.3-py3-none-any.whl";
      sha256 = "1l70fk4fvjwqra0v19qzj0ha8fkcy0kkwrdf33c1ilmkcxdy7f0x";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "pycodestyle" = super.buildPythonPackage rec {
    pname = "pycodestyle";
    version = "2.13.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/07/be/b00116df1bfb3e0bb5b45e29d604799f7b91dd861637e4d448b4e09e6a3e/pycodestyle-2.13.0-py2.py3-none-any.whl";
      sha256 = "1a9v2ig8mxd6v46cbn39yffz9npnlha8l8pd4skwfwd2fickr1im";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "pycparser" = super.buildPythonPackage rec {
    pname = "pycparser";
    version = "2.22";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/13/a3/a812df4e2dd5696d1f351d58b8fe16a405b234ad2886a0dab9183fb78109/pycparser-2.22-py3-none-any.whl";
      sha256 = "1k6gk7j4s3s7fpflxhndhsyx18ak7pkdfrd5mz0spiyq7mnjnw63";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "pydantic" = super.buildPythonPackage rec {
    pname = "pydantic";
    version = "2.11.4";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/e7/12/46b65f3534d099349e38ef6ec98b1a5a81f42536d17e0ba382c28c67ba67/pydantic-2.11.4-py3-none-any.whl";
      sha256 = "1sv4cx896ml8zyrqhih2nnpq8sip2vychjd93m3n7865kam5wqfr";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."annotated-types"
      self."pydantic-core"
      self."typing-extensions"
      self."typing-inspection"
    ];
  };
  "pydantic-core" = super.buildPythonPackage rec {
    pname = "pydantic-core";
    version = "2.33.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ad/88/5f2260bdfae97aabf98f1778d43f69574390ad787afb646292a638c923d4/pydantic_core-2.33.2.tar.gz";
      sha256 = "1k3shazldnwv99y35nfi3dy2s53lchp0sd85n7hpd4f20lvbrf3w";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."typing-extensions"
    ];
  };
  "pyflakes" = super.buildPythonPackage rec {
    pname = "pyflakes";
    version = "3.3.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/15/40/b293a4fa769f3b02ab9e387c707c4cbdc34f073f945de0386107d4e669e6/pyflakes-3.3.2-py2.py3-none-any.whl";
      sha256 = "0an3ln10zla8jfack7697kqq0qch11lldrafbw2486dvkhrwhfah";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "pygments" = super.buildPythonPackage rec {
    pname = "pygments";
    version = "2.19.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/8a/0b/9fcc47d19c48b59121088dd6da2488a49d5f72dacf8262e2790a1d2c7d15/pygments-2.19.1-py3-none-any.whl";
      sha256 = "133dmda902c3wcg63c1lf1jwxfwkbb9nvarg4jwg9v2wsm5598cy";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "pylint" = super.buildPythonPackage rec {
    pname = "pylint";
    version = "3.3.6";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/31/21/9537fc94aee9ec7316a230a49895266cf02d78aa29b0a2efbc39566e0935/pylint-3.3.6-py3-none-any.whl";
      sha256 = "19m6l1d2g9n3sw2gb4arfxwb7dmrs0fm4gbh4zxr8gxfhqz2sz4b";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."astroid"
      self."dill"
      self."isort"
      self."mccabe"
      self."platformdirs"
      self."tomli"
      self."tomlkit"
      self."typing-extensions"
    ];
  };
  "pyparsing" = super.buildPythonPackage rec {
    pname = "pyparsing";
    version = "3.2.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/05/e7/df2285f3d08fee213f2d041540fa4fc9ca6c2d44cf36d3a035bf2a8d2bcc/pyparsing-3.2.3-py3-none-any.whl";
      sha256 = "1kxzwbvmxj81y8y3wf0c16xi88wq4i551jjnndchpzfn0a796jd7";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "pytest" = super.buildPythonPackage rec {
    pname = "pytest";
    version = "8.3.5";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/30/3d/64ad57c803f1fa1e963a7946b6e0fea4a70df53c1a7fed304586539c2bac/pytest-8.3.5-py3-none-any.whl";
      sha256 = "086qsjsc0yab2pz7cca0daqzvaf4p68gb962svx2kb6y8ym194n6";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."exceptiongroup"
      self."iniconfig"
      self."packaging"
      self."pluggy"
      self."tomli"
    ];
  };
  "python-dateutil" = super.buildPythonPackage rec {
    pname = "python-dateutil";
    version = "2.9.0.post0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ec/57/56b9bcc3c9c6a792fcbaf139543cee77261f3651ca9da0c93f5c1221264b/python_dateutil-2.9.0.post0-py2.py3-none-any.whl";
      sha256 = "09q48zvsbagfa3w87zkd2c5xl54wmb9rf2hlr20j4a5fzxxvrcm8";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."six"
    ];
  };
  "pywayland" = super.buildPythonPackage rec {
    pname = "pywayland";
    version = "0.4.18";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/20/93/bc9b258dcb46aafc587438355a9170c3be05a6abb5cd55bf1d600d848fa0/pywayland-0.4.18.tar.gz";
      sha256 = "0cv5aqn23id31mn95q6isn5vcnjcd4dvaqzn52ihbb9sg01dx2jr";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [
      self."setuptools"
      self."wheel"
      self."cffi"
    ];
    propagatedBuildInputs = [
      self."cffi"
    ];
  };
  "pyyaml" = super.buildPythonPackage rec {
    pname = "pyyaml";
    version = "6.0.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/54/ed/79a089b6be93607fa5cdaedf301d7dfb23af5f25c398d5ead2525b063e17/pyyaml-6.0.2.tar.gz";
      sha256 = "0gmwggzm0j0iprx074g5hah91y2f68sfhhldq0f8crddj7ndk16m";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "pyzmq" = super.buildPythonPackage rec {
    pname = "pyzmq";
    version = "26.4.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/b1/11/b9213d25230ac18a71b39b3723494e57adebe36e066397b961657b3b41c1/pyzmq-26.4.0.tar.gz";
      sha256 = "0vb2biwl9kss5f12gwljg9gilybj0kz5cwqscldgjqh9z22kzlab";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "requests" = super.buildPythonPackage rec {
    pname = "requests";
    version = "2.32.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/f9/9b/335f9764261e915ed497fcdeb11df5dfd6f7bf257d4a6a2a686d80da4d54/requests-2.32.3-py3-none-any.whl";
      sha256 = "1inwsrhx0m16q0wa1z6dfm8i8xkrfns73xm25arcwwy70gz1qxkh";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."certifi"
      self."charset-normalizer"
      self."idna"
      self."urllib3"
    ];
  };
  "scipy" = super.buildPythonPackage rec {
    pname = "scipy";
    version = "1.13.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ae/00/48c2f661e2816ccf2ecd77982f6605b2950afe60f60a52b4cbbc2504aa8f/scipy-1.13.1.tar.gz";
      sha256 = "0g7dfjw18c00hh5qq6wkzh01iid8239vnp0mlvbdy21b66h8fnh9";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."numpy"
    ];
  };
  "sentry-sdk" = super.buildPythonPackage rec {
    pname = "sentry-sdk";
    version = "2.27.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/dd/8b/fb496a45854e37930b57564a20fb8e90dd0f8b6add0491527c00f2163b00/sentry_sdk-2.27.0-py2.py3-none-any.whl";
      sha256 = "1w3g466i1k83xwiwhbk35cf2icy7vgmsvs1pdn2s1xlazyzkb2f5";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."certifi"
      self."urllib3"
    ];
  };
  "setproctitle" = super.buildPythonPackage rec {
    pname = "setproctitle";
    version = "1.3.6";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/9e/af/56efe21c53ac81ac87e000b15e60b3d8104224b4313b6eacac3597bd183d/setproctitle-1.3.6.tar.gz";
      sha256 = "0sci81l0kvmjgzswwli7v1fx62dn9fahgkzp6d7kifq0qyb2pwy9";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "six" = super.buildPythonPackage rec {
    pname = "six";
    version = "1.17.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/b7/ce/149a00dd41f10bc29e5921b496af8b574d8413afcd5e30dfa0ed46c2cc5e/six-1.17.0-py2.py3-none-any.whl";
      sha256 = "0x1jdic712dylbnyiqdj4xyxrlx0gaacynmbmkfiym4hxn8z68a7";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "smmap" = super.buildPythonPackage rec {
    pname = "smmap";
    version = "5.0.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/04/be/d09147ad1ec7934636ad912901c5fd7667e1c858e19d355237db0d0cd5e4/smmap-5.0.2-py3-none-any.whl";
      sha256 = "0pmg0dab5kqr116xpab0n9srx1wd9016byx048fm7mzpvvq1a0dk";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "stack-data" = super.buildPythonPackage rec {
    pname = "stack-data";
    version = "0.6.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/f1/7b/ce1eafaf1a76852e2ec9b22edecf1daa58175c090266e9f6c64afcd81d91/stack_data-0.6.3-py3-none-any.whl";
      sha256 = "15g627jndkgqp68rz7yxhp5hh6l9m5yxglysrm9hijx44l68wmfm";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."asttokens"
      self."executing"
      self."pure-eval"
    ];
  };
  "tblib" = super.buildPythonPackage rec {
    pname = "tblib";
    version = "3.1.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/27/44/aa5c8b10b2cce7a053018e0d132bd58e27527a0243c4985383d5b6fd93e9/tblib-3.1.0-py3-none-any.whl";
      sha256 = "0klqbrkib7fcmsxnr3nlyclv8a3104dzljm8h4yln4vq4mcb82v7";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "tomli" = super.buildPythonPackage rec {
    pname = "tomli";
    version = "2.2.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/6e/c2/61d3e0f47e2b74ef40a68b9e6ad5984f6241a942f7cd3bbfbdbd03861ea9/tomli-2.2.1-py3-none-any.whl";
      sha256 = "1k45vj5659ghprcb5rvxlx3z3jdrcbvzkvpk1jfpf224bwycfmfb";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "tomlkit" = super.buildPythonPackage rec {
    pname = "tomlkit";
    version = "0.13.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/f9/b6/a447b5e4ec71e13871be01ba81f5dfc9d0af7e473da256ff46bc0e24026f/tomlkit-0.13.2-py3-none-any.whl";
      sha256 = "1ppg0dgipz5f9f9xp4z72in9lx7ggfpbxfqgcxzij6g1yqkl95vs";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "tornado" = super.buildPythonPackage rec {
    pname = "tornado";
    version = "6.4.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/59/45/a0daf161f7d6f36c3ea5fc0c2de619746cc3dd4c76402e9db545bd920f63/tornado-6.4.2.tar.gz";
      sha256 = "02v2mlvr58xg0l0gh08nswl53z73wkf23sziggypk63ffjsdbflj";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "tqdm" = super.buildPythonPackage rec {
    pname = "tqdm";
    version = "4.67.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/d0/30/dc54f88dd4a2b5dc8a0279bdd7270e735851848b762aeb1c1184ed1f6b14/tqdm-4.67.1-py3-none-any.whl";
      sha256 = "1qldljk9pzxx05b3xrh1xaih3n2c8vaq1mg0hhlfg0lg7355wi16";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "traitlets" = super.buildPythonPackage rec {
    pname = "traitlets";
    version = "5.14.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/00/c0/8f5d070730d7836adc9c9b6408dec68c6ced86b304a9b26a14df072a6e8c/traitlets-5.14.3-py3-none-any.whl";
      sha256 = "0kxcy67nh9jl2k590c717p5l0rmsb6ksxdqxhg62ivdijziqjkmp";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "typing-extensions" = super.buildPythonPackage rec {
    pname = "typing-extensions";
    version = "4.13.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/8b/54/b1ae86c0973cc6f0210b53d508ca3641fb6d0c56823f288d108bc7ab3cc8/typing_extensions-4.13.2-py3-none-any.whl";
      sha256 = "134g82hs8v6krn6f550n77fbpbawflhsmgp2sgjw7zj99g0fffd4";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "typing-inspection" = super.buildPythonPackage rec {
    pname = "typing-inspection";
    version = "0.4.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/31/08/aa4fdfb71f7de5176385bd9e90852eaf6b5d622735020ad600f2bab54385/typing_inspection-0.4.0-py3-none-any.whl";
      sha256 = "0bw3hq9xd4yqxs804r8cjjn9zjxgwq8fd9zp35x3d9njzicjbrsh";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."typing-extensions"
    ];
  };
  "urllib3" = super.buildPythonPackage rec {
    pname = "urllib3";
    version = "2.4.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/6b/11/cc635220681e93a0183390e26485430ca2c7b5f9d33b15c74c2861cb8091/urllib3-2.4.0-py3-none-any.whl";
      sha256 = "04z8sxfmrpzir7562cy0354mhslm2mjadm02qw00j2ln9186c5jf";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "wandb" = super.buildPythonPackage rec {
    pname = "wandb";
    version = "0.19.10";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/c7/1b/39261dbbfa35b2d4f21656dca87b7b43eea7a8e0cfec6ad1514faed6e8d3/wandb-0.19.10.tar.gz";
      sha256 = "1frn2i7zy8zfwdbbrc4np98f0gfmkbasij70nzifwnfjdk9741q1";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."click"
      self."docker-pycreds"
      self."eval-type-backport"
      self."gitpython"
      self."platformdirs"
      self."protobuf"
      self."psutil"
      self."pydantic"
      self."pyyaml"
      self."requests"
      self."sentry-sdk"
      self."setproctitle"
      self."setuptools"
      self."typing-extensions"
    ];
  };
  "wcwidth" = super.buildPythonPackage rec {
    pname = "wcwidth";
    version = "0.2.13";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/fd/84/fd2ba7aafacbad3c4201d395674fc6348826569da3c0937e75505ead3528/wcwidth-0.2.13-py2.py3-none-any.whl";
      sha256 = "0nb89xwaqyhi09hqvnvb3hn047lgjkzjj60k6apq83alwi4919ix";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "zipp" = super.buildPythonPackage rec {
    pname = "zipp";
    version = "3.21.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/b7/1a/7e4798e9339adc931158c9d69ecc34f5e6791489d469f5e50ec15e35f458/zipp-3.21.0-py3-none-any.whl";
      sha256 = "0cfr7hmx88sji1ai52chvj1ivlgnqnxgy96fxdhg3499zl2vw6xc";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
}
