wandb_project: "hippo-cartpole"

env:
  name: cartpole
  gamma: 0.96
  # These arguments are passed to the environment constructor
  cfg:
    full_obs_key: "observation"
    safety_obs_key: "observation"
    max_steps: 249 # < episode_len_sec/pyb_freq
    num_parallel_env: 8  #rule of thumb: <=frames_per_batch / max_steps
    params:
      max_input: 1.0
models:
  cdf_net:
    name: feedforward
    eps: 1.0e-3
    layers: [64, 64]
    activation: relu 

  value_net:
    name: feedforward
    eps: 0.0
    layers: [64, 64]
    activation: relu

  policy_net:
    name: feedforward
    layers: [64, 64]
    activation: relu

algorithm:
  name: hippo
  num_epochs: 10
  frames_per_batch: 4096   # 2**12
  sub_batch_size: 256      # 2**8
  max_grad_norm: 1.0
  total_frames: 1048576     # 2**20
  clip_epsilon: 0.2
  lmbda1: 0.1
  lmbda2: 0.95
  critic_coef: 1.0
  supervision_coef: 1.0
  collision_buffer_size: 4096  # same as frames_per_batch
  primary_reward_key: neg_cost
  secondary_reward_key: reward
  entropy_coef: 0.001
  loss_critic_type: smooth_l1
  optim_kwargs:
    lr: 1.0e-4
  scheduler:
    name: cosine
    last_epoch: -1
    eta_min: 1.0e-6

evaluation:
  eval_steps: 300
  track_bellman_violation: false

render:
  render: true
  num_frames: 1000
  fps : 30
